"""Centralized configuration constants for the Sentinel AI pipeline."""

# Detection
MODEL_PATH = "yolov8n.pt"
CONF_THRESHOLD = 0.5

# Tracker
TRACKER_MAX_DISAPPEARED = 50
TRACKER_MAX_DISTANCE = 120
TRACKER_MIN_IOU = 0.15

# Event engine (EventEngineConfig defaults)
EVENT_HISTORY_SIZE = 60
EVENT_SMOOTHING_WINDOW = 5
EVENT_RAPID_SPEED_THRESHOLD = 25.0
EVENT_RAPID_MIN_FRAMES = 3
EVENT_LOITER_SPEED_THRESHOLD = 3.0
EVENT_LOITER_MIN_FRAMES = 45
EVENT_SUDDEN_STOP_PREV_SPEED_THRESHOLD = 20.0
EVENT_SUDDEN_STOP_CURRENT_SPEED_THRESHOLD = 3.0
EVENT_COOLDOWN_FRAMES = 20
